name: elia_hackathon_2024_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_icons: 1.0.2
  dio: 5.4.2
  equatable: 2.0.5
  flutter:
    sdk: flutter
  flutter_animate: 4.5.0
  flutter_map: 6.1.0
  flutter_map_cancellable_tile_provider: 2.0.0
  flutter_map_location_marker: 8.0.8
  flutter_riverpod: 2.5.1
  flutter_svg: 2.0.10+1
  go_router: 13.2.1
  google_fonts: 6.0.0
  json_annotation: 4.8.1
  latlong2: 0.9.0
  pretty_dio_logger: 1.3.1
  retrofit: 4.1.0
  riverpod_annotation: 2.3.5
  wolt_modal_sheet: 0.5.0

dev_dependencies:
  build_runner:
  custom_lint:
  flutter_lints: 2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: 6.7.1
  retrofit_generator: 8.1.0
  riverpod_generator: 2.4.0
  riverpod_lint: 2.3.10

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
